Add GET /about API support
darrarski/swift-google-drive-client pull request #21
Opened 2024-03-09 02:17 UTC by idolize

Hi thanks for this project!

I'm trying to use the [`about.get` API](https://developers.google.com/drive/api/reference/rest/v3/about/get) to load some information about the user, so I thought I'd go ahead and submit a PR to make that an option in the library.

I tried to follow all the existing conventions and added tests as well (although I did not add this function to the example app). I also verified all tests (including old tests) pass.

![test results](https://github.com/darrarski/swift-google-drive-client/assets/635005/4f503f3f-5262-4fbc-b7ae-43a0583bdc69)

2024-03-13 09:44 UTC, darrarski commented
Hello @idolize! Thanks for your great contribution. There is only one small issue with unit tests: `GetAboutTests.testGetAbout` is failing because of a wrong assertion against the request URL. It's easy to fix:

**file:** `Tests/GoogleDriveClientTests/GetAboutTests.swift`
**line:** 61

```diff
- let url = URL(string: "https://www.googleapis.com/drive/v3/about")!
+ let url = URL(string: "https://www.googleapis.com/drive/v3/about?fields=\(About.apiFields)")!
```

I guess you just forgot to include the `fields` query parameter to the expected URL. With the above change, tests will pass. I'm happy to merge the PR and release a new version that includes your changes once the issue is fixed.

Thanks again for contributing!

2024-03-13 09:46 UTC, darrarski requested changes
Nice contribution!

Please fix the expected URL in `GetAboutTests.testGetAbout` test (see my comment for details).

2024-03-13 09:46 UTC, darrarski commented on Tests/GoogleDriveClientTests/GetAboutTests.swift
> +      let url = URL(string: "https://www.googleapis.com/drive/v3/about")!
```suggestion
      let url = URL(string: "https://www.googleapis.com/drive/v3/about?fields=\(About.apiFields)")!
```

2024-03-13 14:41 UTC, idolize commented
Thanks, I made a change and forgot to update that part of the test.

Should be fixed now!

![image](https://github.com/darrarski/swift-google-drive-client/assets/635005/fa01d1f1-e265-4613-be65-61d7dd6cc23a)

2024-03-13 14:46 UTC, idolize commented
Also, I wasn't sure if you want to add this function to the README as well or not

2024-03-14 10:11 UTC, darrarski commented
Thanks! I will update the README once merged.

2024-03-14 10:12 UTC, darrarski approved these changes
Great job, thank you!

2024-03-14 10:14 UTC, merged